### PR TITLE
Fix Intersect

### LINKED ISSUE #10: Collision check on heightmap not working properly.
With the current implementation the collision check finds more collisions than there are in actuality. 

Intuitively if one has a round robot with radius 0.2 then 
`collision = heightmap->intersect(robot_pose.t, 0.2)` 
should indicate a collision with the heightmap. In actuality it finds collisions with a radius larger than this 0.2 in the simulator. 

Unknown if this is a bug in the simulator's construction of the heightmap or in geolib's implementation of the intersect function for composite shapes.

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
@KdVos @rmbeumer please have a look at this.

Use the `bug/collisiondetection` branch to run with print statements.

I am not 100% sure about the surface check part. Though the project point q seems to be correct. But definitely not really sure about the cross/dot products in the end.
_Update_: I think we are doing https://www.baeldung.com/cs/check-if-point-is-in-2d-triangle#1-mathematical-idea-2. I am not really sure why we need the dot product there, but I think it does roughly the same as returning 1/-1.

Fixes https://github.com/tue-robotics/emc_simulator/issues/10

### CODE REVIEW

File: src/Shape.cpp [hunk 1]
```diff
@@ -10,6 +10,27 @@
 
 namespace geo {
 
+/**
+ * @brief Check whether a point p is within distance radius of the line segment whose first vertex is described by ${v} and second vertex by ${v-e}
```
Comment (KdVos) [inline src/Shape.cpp]: Vertex ${v} and ${v-e}? Change comment/documentation according to current variable naming

File: src/Shape.cpp [hunk 2]
```diff
@@ -10,6 +10,27 @@
...
+ * @param p Point to check
+ * @param radius2 Radius squared to check with
+ * @param a Starting point of linesegment
+ * @param ab Linesegment from A to B
+ * @return
+ */
+bool check_linesegment(const Vector3& p, const double radius2, const Vector3& a, const Vector3& ab) {
+    geo::Vector3 ap = p-a;
+    double d1_2 = ap.length2();  // Distance between v and p, squared
```
Comment (KdVos) [inline src/Shape.cpp]:
```suggestion
    double d1_2 = ap.length2();  // Distance between a and p, squared
```

File: src/Shape.cpp [hunk 3]
```diff
@@ -28,74 +49,72 @@ bool Shape::intersect(const Ray& /*r*/, float /*t0*/, float /*t1*/, double& /*di
...
-    double d2 = e.dot(v-p);  // dot product between e and v-p
-    if (d2>0) {
-        d2 = d2*d2 / e.length2(); // distance between v and the projection of p on e
-        return d1-d2 < radius && d2 < e.length2();
-    }
-    return false;
-}
-
 /**
  *  @math http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.49.9172&rep=rep1&type=pdf
```
Comment (PetervDooren) [inline src/Shape.cpp:54]: In your commit msgs I saw you used another source. Please cite that source so we can see which conventions are followed.

**Review by PetervDooren — CHANGES_REQUESTED** [review]
I disagree with commit 044d00b2753cd89f7481dd0bb89571c53c139a8f.
Implementation was not bad and shuffling around functions and formatting does not 'fix' anything. :P 
But other than the commit message I think its alright

**Comment by MatthijsBurgh** [comment]
> I disagree with commit [044d00b](https://github.com/tue-robotics/geolib2/commit/044d00b2753cd89f7481dd0bb89571c53c139a8f). Implementation was not bad and shuffling around functions and formatting does not 'fix' anything. :P But other than the commit message I think its alright

Changing the order of subtraction and adding missing multiplications does fix shit.

**Comment by MatthijsBurgh** [comment]
DO NOT MERGE: Need to restore the  `contains(p)` at the end of `intersect`

**Comment by MatthijsBurgh** [comment]
When merging this one with #60, all tests succeed.

File: src/Shape.cpp [hunk 4]
```diff
@@ -10,6 +10,27 @@
...
 
+/**
+ * @brief Check whether a point p is within distance radius of the line segment. The starting point is described by @b a and the vector from the starting point to the end point @b ab
+ * @param p Point to check
+ * @param radius2 Radius squared to check with
+ * @param a Starting point of linesegment
+ * @param ab Linesegment from A to B
+ * @return
+ */
+bool check_linesegment(const Vector3& p, const double radius2, const Vector3& a, const Vector3& ab) {
```
Comment (PetervDooren) [inline src/Shape.cpp:21]: In the contains PR you introduced a custom class for line segments. Perhaps it would be better to include that as an input to this function as well

File: src/Shape.cpp [hunk 5]
```diff
@@ -10,6 +10,27 @@
...
+    geo::Vector3 ap = p-a;
+    double d1_2 = ap.length2();  // Distance between a and p, squared
+    double d2 = ab.dot(ap);  // Dot product between ab and ap; projection of p on linesegment ab
+
+    if (d2 < 0)
+        // If ab dot ap < 0, there can't be any intersection, because the orientated linesegment points away
```
Comment (PetervDooren) [inline src/Shape.cpp:27]: It can given a sufficiently large radius.

File: src/Shape.cpp [hunk 6]
```diff
@@ -10,6 +10,27 @@
 
 namespace geo {
 
+/**
+ * @brief Check whether a point p is within distance radius of the line segment. The starting point is described by @b a and the vector from the starting point to the end point @b ab
```
Comment (PetervDooren) [inline src/Shape.cpp:14]: One property of this function which is not readily apparant is that it will return true only if the projection of p on line ab lies within the line segment ab. 
The reason for this is that we have already checked the endpoints of the lines in the main function.

Comment (PetervDooren) [inline src/Shape.cpp:14]: One property of this function which is not readily apparant is that it will return true only if the projection of p on line ab lies within the line segment ab. 
The reason for this is that we have already checked the endpoints of the lines in the main function.

**Review by PetervDooren — APPROVED** [review]
Some suggestions which may improve the PR. But good nonetheless

File: src/Shape.cpp (hunk 5 above)
Comment (MatthijsBurgh) [reply src/Shape.cpp:27]: This is covered by other parts of the code.

File: src/Shape.cpp (hunk 4 above)
Comment (MatthijsBurgh) [reply src/Shape.cpp:21]: I will check if this is possible in the other PR.

Comment (MatthijsBurgh) [reply src/Shape.cpp:21]: I will check if this is possible in the other PR.

File: src/Shape.cpp (hunk 6 above)
Comment (MatthijsBurgh) [reply src/Shape.cpp:14]: I will check this in the other PR.
